### PR TITLE
utf-8 encoding for plugin

### PR DESCRIPTION
**Pull request by bbaronSVK**
niektore nazvy sa kvoli nenastavenmu encodovaniu na utf-8 nezobrazovali. Teraz je uz vsetko OK.

---

This change is [Reviewable](https://reviewable.io/reviews/kodi-czsk/plugin.video.sosac.ph/77)

### CODE REVIEW

**Comment by bbaronSVK** [comment]
formatovanie v pythone mi nejde....vie to niekto pls opravit?

**Comment by lubo** [comment]
Akoze ti to nejde ? Vsak to prezen nejakym beautifierom. Ak pouzivas Atom, tak atom-beautify funguje uplne skvele.

**Comment by lubo** [comment]
b2f2cdc uz bol aplikovany ako 66afc6ca483bee197dd0112ed7041b836cf09c15. Neviem, ze ci si necital vysledky predosleho merge requestu... V kazdom pripade, vzdy by si mal pracovat v novej branchy vytvorenej z upstream mastera. Uprac to, prosim.

**Comment by bbaronSVK** [comment]
nechcem zasa formatovat komplet vsetko, len tie moje zmeny

**Comment by lubo** [comment]
Preco nie ? Ak mas dobre nastaveny beautifier, tak by to nemalo nic ine zmenit, pretoze vsetko ostatne uz followuje PEP8 a nase vynimky.

**Comment by lubo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[resources/lib/sosac.py, line 33 at r1](https://reviewable.io:443/reviews/kodi-czsk/plugin.video.sosac.ph/77#-KRd-FeYnXtzGpIXlVDk:-KRd-FeYnXtzGpIXlVDl:b-trkt0u) ([raw file](https://github.com/kodi-czsk/plugin.video.sosac.ph/blob/fe1014cd86cb11c681f484be9dd132dd775aeebf/resources/lib/sosac.py#L33)):_

> ``` Python
> from provider import ContentProvider, cached, ResolveException
> 
> reload(sys)
> ```

K comu je toto dobre ?

---

_[resources/lib/sosac.py, line 35 at r1](https://reviewable.io:443/reviews/kodi-czsk/plugin.video.sosac.ph/77#-KRd-iFJjRSGj4JLu26L:-KRd-iFJjRSGj4JLu26M:b1tfjz) ([raw file](https://github.com/kodi-czsk/plugin.video.sosac.ph/blob/fe1014cd86cb11c681f484be9dd132dd775aeebf/resources/lib/sosac.py#L35)):_

> ``` Python
> reload(sys)
> sys.setrecursionlimit(10000)
> sys.setdefaultencoding('utf-8')
> ```

Preco radsej nepridat `# -*- coding: utf-8 -*-` na zaciatok suboru ?

---

_[resources/lib/sosac.py, line 247 at r1](https://reviewable.io:443/reviews/kodi-czsk/plugin.video.sosac.ph/77#-KRd0NZNkelb4jy2rUw7:-KRd0NZOX1uyqqwJN7Rk:beih1w6) ([raw file](https://github.com/kodi-czsk/plugin.video.sosac.ph/blob/fe1014cd86cb11c681f484be9dd132dd775aeebf/resources/lib/sosac.py#L247)):_

> ``` Python
>             item['art'] = {'fanart': 'http://csfd.bbaron.sk/xbmc.php?%s' % (urllib.urlencode(f))}
> 
>             self._filter(result, item)
> ```

Preco si tento blok vybral z try/except ?

---

_[resources/lib/sosac.py, line 410 at r1](https://reviewable.io:443/reviews/kodi-czsk/plugin.video.sosac.ph/77#-KRd0TxbgzQe_eFHJaYs:-KRd0TxbgzQe_eFHJaYt:bkdoch2) ([raw file](https://github.com/kodi-czsk/plugin.video.sosac.ph/blob/fe1014cd86cb11c681f484be9dd132dd775aeebf/resources/lib/sosac.py#L410)):_

> ``` Python
>                 item['update'] = True
>                 item['notify'] = False
>                 self.parent.add_item(item)
> ```

Znova, preco si tento blok vybral z try/except ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/plugin.video.sosac.ph/77)_

**Comment by bbaronSVK** [comment]
`# -*- coding: utf-8 -*-` tam uz bolo, ale nefungovalo to. Tak som niekde na webe nasiel, ze treba pouzit 

```
reload(sys)
sys.setrecursionlimit(10000)
sys.setdefaultencoding('utf-8')
```

tak som to tam pridal a zafungovalo to. try/except som tam pridaval preto, lebo mi nefungovali utf-8 nazvy, takze teraz ked uz funguju, tak som to vyhodil.

**Comment by lubo** [comment]
No, ja tam vidim `# -*- coding: UTF-8 -*-` a nie `# -*- coding: utf-8 -*-`. Mozno to ma problem s tym `UTF-8`.

**Comment by ExSport** [comment]
@Kuci @bbaronSVK A ja kdyz troubleshootoval chybejici diaktriku https://github.com/kodi-czsk/plugin.video.sosac.ph/issues/67 tak jsem jen nasel, ze podminka je to umistit na prvni nebo druhy radek. Zkousel jsem to a fungovalo me to...
EDIT: jen uz nevim zda jsem pouzil UTF8/utf8/UTF-8 ci utf-8 :) Zminuju to jen proto, ze me napadlo, zda jsi to mozna umistil nize nez na 1. nebo 2. radek :)

**Comment by ExSport** [comment]
@bbaronSVK 
Dik, opravdu ted vidi i to co predtim nevidel, napr. "Kazdy milion dobry", ale zobrazuje navic na konci nazvu kvalitu videa, coz v pripade pridani do knihovny (jednotlivě) zdvojuje polozky.
Netyka se to fce "Add all to library", ktera videla tyto polozky i bez tohoto patche a taktez i po tomto patchi kvalitu do nazvu adresare/souboru nepridava (nevznikaji duplicity).
Mimochdem, ta kvalita se pridava jen do kategorie "Movies" a "Movies - by Genres".
Ne do "Movies - Most popular" a "Movies - Recently added". Z toho vyvozuji bez kontroly kodu, ze tyto kategorie tento patch neresi, tedy nektere polozky zde stale nemusi byt videt.
**EDIT:** Beru zpet tu cast, ze neco nepujde videt. Ty ostatni fce jiz mely **encode('utf-8')**, takze please jen uprav at se do knihovny prida **item['title']** bez priznaku **kvality**.
Dik :+1:

**Comment by bbaronSVK** [comment]
s encode('utf-8') to hadzalo chybu, kedze python takmer vobec nepoznam, tak neviem preco to blblo. To, ze `Add all to library` funguje so vsetkymi filmami je divne, musim pozriet ako som to tam robil.

**Comment by ExSport** [comment]
@bbaronSVK Tu fci jsem prepisoval, viz: https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/50
Tuto jsem nově pridal **def library_movies_all_xml**, aby parsovala vse a fungovala i bez UTF-8 codepage samotneho python souboru.
To bylo potreba zmenit jen ve chvili, kdyz potrebujes mit utf-8 znak primo v kodu, coz neni treba, proto si myslim, ze tvuj pull by fungoval jen s pouzitim **.encode('utf-8')** a bez nutnosti definovat, ze cely .py soubor je utf-8.
Alespon teda kompiler te upozorni jen ve chvili, kdyz do non-UTF8/CP1250/... nacpes takovy znak a on ho neumi interpretovat :)
Nejsem ale programator takze treba pisu nesmysly (mam jen vseoobecne zaklady programovani a scriptovani, proste server admin) :+1:

**Pull request closed without merging**
